export class Picture{
  Date_Time !: any;
  ID !: any;
  altitude !: any;
  aperture_value !: any;
  bits_per_px !: any;
  cam_bright !: any;
  cam_exposure !: any;
  cam_focal !: any;
  cam_manufacturer !: any;
  cam_model !: any;
  comment !: any;
  compression !: any;
  copyright !: any;
  creation_date !: any;
  date_time_dig !: any;
  date_time_orig !: any;
  endian !: any;
  exif_ver !: any;
  exposure_bias !: any;
  flashpix_ver !: any;
  focal_length !: any;
  focal_length_35mm !: any;
  format_ver !: any;
  height !: any;
  height_dpi !: any;
  img_orient !: any;
  iso_speed_ratings !: any;
  latitude !: any;
  longitude !: any;
  mime_type !: any;
  px_format !: any;
  producer !: any;
  shutter_speed !: any;
  thumbnail_size !: any;
  width !: any;
  width_dpi !: any;

}
